### ISSUE TITLE
3.4 default value for String format

### ISSUE THREAD

**Issue by deata** [Microsoft/ODBC-Specification#112]
Text/Plain ?

**Comment by mikepizzo** [comment]
should probably default to empty string, so client can differentiate between "Text/Plain" and "Unknown".  This is consistent with how Content-Type is handled in HTTP.

**Comment by mikepizzo** [comment]
fixed in spec:

A new SQLCHAR\*-valued descriptor field, `SQL_DESC_MIME_TYPE`, is added to \[ALL\] descriptors to specify the format of a field or parameter whose `SQL_DESC_TYPE` specifies a string or binary type. The value of this descriptor field is the mime type of the data (i.e., application/json, application/xml,…), or an empty string if the field or parameter is not a string or binary type, or if the format is not known.
